services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pokejob
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "3307:3306"

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ../public:/var/www/html
      - ../app:/var/www/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: pokejob
      DB_USER: root
      DB_PASSWORD: rootpassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword

volumes:
  db_data: